variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: gp600
  JAR_FILE: target/gp600.jar
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

stages:
  - package
  - deploy

package-job:
  image: maven:3-jdk-8
  stage: package
  script:
    - "mvn $MAVEN_CLI_OPTS clean package -P gitlab-ci"
  artifacts:
    paths:
      - target/*.jar

deploy-job:
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--insecure-registry=repo.ivynative.com"]

  stage: deploy
  script:
    - "docker build -t repo.ivynative.com/tox/$DOCKER_IMAGE ."
    - "docker login -u $DOCKER_CI_USER -p $DOCKER_CI_TOKEN repo.ivynative.com"
    - "docker push repo.ivynative.com/tox/$DOCKER_IMAGE"